name: 'Build and Push image'
description: 'Composite action to generate images'
inputs:
  registry:
    description: 'Image registry to use'
    required: true
    default: 'ghcr.io'
  username:
    description: 'Username to the image registry'
    required: true
  password:
    description: 'Password for the image registry'
    required: true
  image:
    description: 'Docker image to build'
    required: true
  context:
    description: 'Context to docker build'
    required: true
    default: "."
  file:
    description: 'Path to the docker file relative to context'
    required: true
  build-args:
    description: 'Build arguments for docker'
    required: false
runs:
  using: "composite"
  steps:
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.registry }}/${{ inputs.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=schedule,pattern=nightly
          type=raw,latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}
