name: Publish docker images

on:
  schedule:
    - cron: '0 0 * * 1' # Monday 12:00 UTC
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ] # semver release
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REPOSITORY_OWNER: ${{github.repository_owner}}

jobs:

  build-flutter-builder:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/build-push
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
        image: ${{ env.DOCKER_REPOSITORY_OWNER }}/flutter-builder
        context: ./flutter-builder
        file: flutter-builder/Dockerfile
    
  build-web-server:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/build-push
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
        image: ${{ env.DOCKER_REPOSITORY_OWNER }}/web-server
        context: ./web-server
        file: web-server/Dockerfile

